<!doctype html><html><head><meta charset="utf-8"><title>Rentabilidad {{$order->code}}</title><style>body{font-family:DejaVu Sans,sans-serif;color:#263c36;font-size:10px}h1{font-size:18px;margin:0}.muted{color:#70817c}.header{border-bottom:2px solid #168b78;padding-bottom:10px;margin-bottom:14px}.grid{width:100%;border-collapse:separate;border-spacing:6px}.metric{border:1px solid #dce8e4;padding:9px;border-radius:6px}.metric span{display:block;color:#71817c}.metric strong{font-size:14px}table.data{width:100%;border-collapse:collapse;margin-top:12px}table.data th,table.data td{padding:6px;border:1px solid #dfe8e5}table.data th{background:#edf6f3}.statement{width:60%;margin:15px auto;border-collapse:collapse}.statement td{padding:7px;border-bottom:1px solid #e2e9e7}.total{font-weight:bold;background:#eef7f4}@media print{.no-print{display:none}}</style></head><body @isset($printMode) onload="window.print()" @endisset>
@php
    $hasInvoiceDocument = fn ($cost) => $cost->documents->contains(fn ($document) =>
        \App\Models\WarehouseEntryExpenseDocument::normalizeType($document->document_type) === 'invoice'
        && filled($document->file_path)
    );
@endphp
<div class="header"><h1>Rentabilidad de OC del Cliente</h1><div class="muted">{{$order->code}} · OC {{$order->purchase_order_number}} · {{$order->customer?->business_name ?: $order->customer?->full_name}}</div><div>Modo: {{$mode==='with_igv'?'Con IGV':'Sin IGV'}} · Generado: {{now()->format('d/m/Y H:i')}}</div></div>
<table class="grid"><tr>@foreach(['Venta considerada'=>$saleValue,'Compra considerada'=>$purchaseValue,'Costos'=>$linkedTotal,'Utilidad neta'=>$net,'Rentabilidad %'=>$percentage] as $label=>$value)<td class="metric"><span>{{$label}}</span><strong>{{$label==='Rentabilidad %'?'':'S/ '}}{{number_format($value,2)}}{{$label==='Rentabilidad %'?'%':''}}</strong></td>@endforeach</tr></table>
<table class="statement"><tr><td>Venta considerada</td><td>S/ {{number_format($saleValue,2)}}</td></tr><tr><td>- Compra considerada</td><td>S/ {{number_format($purchaseValue,2)}}</td></tr><tr class="total"><td>Utilidad bruta</td><td>S/ {{number_format($gross,2)}}</td></tr><tr><td>- Flete / recojo / traslado con comprobante</td><td>S/ {{number_format($freightValue,2)}}</td></tr><tr class="total"><td>Utilidad operativa</td><td>S/ {{number_format($operating,2)}}</td></tr><tr><td>- Impuesto renta estimado ({{$incomeTaxRate}}%)</td><td>S/ {{number_format($incomeTax,2)}}</td></tr><tr><td>- Otros gastos / sin comprobante</td><td>S/ {{number_format($otherTotal,2)}}</td></tr><tr class="total"><td>Utilidad neta</td><td>S/ {{number_format($net,2)}}</td></tr></table>
<h3>Compras a proveedor (normalizadas a soles)</h3><div class="muted">La compra considerada usa el total real, incluido IGV cuando corresponde, y prioriza los importes registrados en Almacén.</div><table class="data"><thead><tr><th>OC proveedor</th><th>Proveedor / artículo</th><th>Moneda compra</th><th>Subtotal</th><th>IGV</th><th>Total compra</th><th>Compra considerada</th><th>Estado</th></tr></thead><tbody>@forelse($supplierItems as $item)@php($supplierStatus=\App\Models\CustomerPurchaseOrder::statusPresentation($item->order_status))<tr><td>{{$item->order_code}}</td><td>{{$item->supplier_name}}<br><span class="muted">{{$item->billing_name_snapshot}}</span></td><td>{{$item->purchase_currency_code ?: '-'}}<br><span class="muted">Origen: {{$item->purchase_currency_symbol}} {{number_format((float)$item->line_total,2)}}</span></td><td>S/ {{number_format((float)$item->purchase_subtotal_pen,2)}}</td><td>S/ {{number_format((float)$item->purchase_igv_pen,2)}}</td><td>S/ {{number_format((float)$item->purchase_total_pen,2)}}</td><td><strong>S/ {{number_format((float)$item->considered_purchase_amount,2)}}</strong><br><span class="muted">{{$item->purchase_amount_source === 'warehouse_entry' ? 'Según Almacén' : 'Según OC proveedor'}}</span></td><td>{{$supplierStatus['label']}}</td></tr>@empty<tr><td colspan="8">Sin compras vinculadas.</td></tr>@endforelse</tbody></table>
<h3>Costos vinculados</h3><div class="muted">El importe considerado corresponde al monto completo registrado. La base y el IGV son informativos.</div><table class="data"><thead><tr><th>Tipo</th><th>Responsable</th><th>Documento</th><th>Clasificación</th><th>Ingreso</th><th>Importe considerado</th><th>Base informativa</th><th>IGV informativo</th><th>Comprobante adjunto</th><th>Observación</th></tr></thead><tbody>@forelse($costs as $cost)@php($recognizedIgv=$cost->affects_igv && \App\Models\WarehouseEntryExpense::supportsIgv($cost->document_type))<tr><td>{{$cost->expense_category==='freight_transport'?'Transporte':'Otros'}}</td><td>{{$cost->provider_name}}</td><td>{{collect([\App\Models\WarehouseEntryExpense::documentTypeLabel($cost->document_type),$cost->document_series,$cost->document_number])->filter()->join(' ')}}</td><td>{{\App\Models\WarehouseEntryExpense::isOfficialDocument($cost->document_type) ? 'Con comprobante oficial' : 'Otros gastos / sin comprobante'}}</td><td>{{$cost->warehouseEntry?->entry_number}}</td><td><strong>{{number_format($cost->total_amount ?: $cost->amount,2)}}</strong></td><td>{{number_format($recognizedIgv ? $cost->taxable_amount : ($cost->total_amount ?: $cost->amount),2)}}</td><td>{{number_format($recognizedIgv ? $cost->igv_amount : 0,2)}}</td><td>{{$hasInvoiceDocument($cost) ? 'Sí' : 'No'}}</td><td>{{$cost->description}}</td></tr>@empty<tr><td colspan="10">Sin costos vinculados.</td></tr>@endforelse</tbody></table>
</body></html>
