<div class="modal fade bank-modal" id="bankDetailModal" tabindex="-1"><div class="modal-dialog modal-xl modal-dialog-centered"><div class="modal-content">
    <div class="modal-header"><div class="d-flex align-items-center"><span class="bank-modal-title-icon"><i class="fas fa-university"></i></span><div><h5 class="modal-title font-weight-bold mb-0" id="bankDetailTitle">Detalle de cuenta</h5><small class="text-muted" id="bankDetailSubtitle"></small></div></div><button class="close" data-dismiss="modal">&times;</button></div>
    <ul class="nav nav-pills bank-detail-tabs"><li class="nav-item"><a class="nav-link active" data-toggle="pill" href="#bankTabSummary"><i class="fas fa-th-large mr-1"></i>Resumen</a></li>@can('admin.banks.movements')<li class="nav-item"><a class="nav-link" data-toggle="pill" href="#bankTabMovements"><i class="fas fa-list mr-1"></i>Movimientos</a></li>@endcan @can('admin.banks.transfers')<li class="nav-item"><a class="nav-link" data-toggle="pill" href="#bankTabTransfers"><i class="fas fa-exchange-alt mr-1"></i>Transferencias</a></li>@endcan @can('admin.banks.reconciliations')<li class="nav-item"><a class="nav-link" data-toggle="pill" href="#bankTabReconciliations"><i class="fas fa-check-double mr-1"></i>Conciliación</a></li>@endcan<li class="nav-item"><a class="nav-link" data-toggle="pill" href="#bankTabTrace"><i class="fas fa-history mr-1"></i>Trazabilidad</a></li></ul>
    <div class="tab-content bank-detail-content"><div id="bankTabSummary" class="tab-pane fade show active"></div><div id="bankTabMovements" class="tab-pane fade"></div><div id="bankTabTransfers" class="tab-pane fade"></div><div id="bankTabReconciliations" class="tab-pane fade"></div><div id="bankTabTrace" class="tab-pane fade"></div></div>
    <div class="modal-footer"><div id="bankDetailExports" class="mr-auto"></div><button class="btn btn-light border btn-sm" data-dismiss="modal">Cerrar</button></div>
</div></div></div>

<div class="modal fade bank-modal" id="bankOpeningModal" tabindex="-1"><div class="modal-dialog modal-md modal-dialog-centered"><div class="modal-content"><form id="bankOpeningForm">
    @csrf<input type="hidden" id="bankOpeningAccountId"><div class="modal-header"><div class="d-flex align-items-center"><span class="bank-modal-title-icon"><i class="fas fa-sliders-h"></i></span><div><h5 class="modal-title font-weight-bold mb-0">Configurar saldo inicial</h5><small class="text-muted" id="bankOpeningAccountLabel"></small></div></div><button class="close" data-dismiss="modal">&times;</button></div>
    <div class="modal-body"><div class="alert alert-info py-2 small"><i class="fas fa-info-circle mr-1"></i>Una reconfiguración anula el asiento inicial anterior y genera su reversa, conservando la trazabilidad.</div><div class="form-row"><div class="form-group col-md-6"><label>SALDO INICIAL *</label><input type="number" step="0.0001" min="0" name="opening_balance" id="bankOpeningAmount" class="form-control" required></div><div class="form-group col-md-6"><label>FECHA *</label><input type="date" name="opening_balance_date" id="bankOpeningDate" class="form-control" required></div><div class="form-group col-md-6 bank-exchange-group"><label>TIPO DE CAMBIO</label><input type="number" step="0.000001" min="0.000001" name="exchange_rate" id="bankOpeningRate" class="form-control"></div><div class="form-group col-12"><label>OBSERVACIÓN</label><textarea name="opening_balance_observation" id="bankOpeningObservation" rows="3" class="form-control text-uppercase"></textarea></div></div></div>
    <div class="modal-footer"><button type="button" class="btn btn-light border btn-sm" data-dismiss="modal">Cancelar</button><button class="btn btn-success btn-sm" type="submit"><i class="fas fa-save mr-1"></i>Guardar saldo</button></div>
</form></div></div></div>

<div class="modal fade bank-modal" id="bankMovementModal" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><form id="bankMovementForm" enctype="multipart/form-data">
    @csrf<input type="hidden" name="direction" id="bankMovementDirection"><div class="modal-header"><div class="d-flex align-items-center"><span class="bank-modal-title-icon"><i class="fas fa-money-check-alt"></i></span><div><h5 class="modal-title font-weight-bold mb-0" id="bankMovementTitle">Registrar movimiento</h5><small class="text-muted">El asiento actualizará el saldo y conservará su origen.</small></div></div><button class="close" data-dismiss="modal">&times;</button></div>
    <div class="modal-body"><div class="form-row"><div class="form-group col-md-6"><label>CUENTA BANCARIA *</label><select name="company_bank_account_id" id="bankMovementAccount" class="form-control" required>@include('admin.banks.partials.account-options')</select></div><div class="form-group col-md-3"><label>FECHA *</label><input type="datetime-local" name="movement_date" id="bankMovementDate" class="form-control" required></div><div class="form-group col-md-3"><label>TIPO *</label><select name="movement_category" id="bankMovementCategory" class="form-control" required></select></div><div class="form-group col-md-3"><label>MONTO *</label><input type="number" step="0.0001" min="0.0001" name="amount" class="form-control" required></div><div class="form-group col-md-3 bank-exchange-group"><label>TIPO DE CAMBIO</label><input type="number" step="0.000001" min="0.000001" name="exchange_rate" class="form-control"></div><div class="form-group col-md-3"><label>N° OPERACIÓN</label><input name="operation_number" class="form-control text-uppercase" maxlength="100"></div><div class="form-group col-md-3"><label>DOCUMENTO</label><input name="document_type" class="form-control text-uppercase" maxlength="50" placeholder="Factura, voucher..."></div><div class="form-group col-md-3"><label>SERIE</label><input name="document_series" class="form-control text-uppercase" maxlength="30"></div><div class="form-group col-md-3"><label>NÚMERO</label><input name="document_number" class="form-control text-uppercase" maxlength="80"></div><div class="form-group col-md-3"><label>FECHA DOCUMENTO</label><input type="date" name="document_date" class="form-control"></div><div class="form-group col-md-6" id="bankMovementSourceGroup"><label>ORIGEN VINCULADO</label><select name="source_id" id="bankMovementSource" class="form-control"><option value="">Seleccione</option></select></div><div class="form-group col-md-6"><label>CONCEPTO *</label><input name="concept" id="bankMovementConcept" class="form-control text-uppercase" maxlength="150" required></div><div class="form-group col-md-6"><label>SUSTENTO</label><div class="custom-file"><input type="file" name="file" id="bankMovementFile" class="custom-file-input" accept=".pdf,.jpg,.jpeg,.png,.webp"><label class="custom-file-label" for="bankMovementFile">Seleccionar archivo</label></div></div><div class="form-group col-12"><label>OBSERVACIÓN</label><textarea name="description" rows="2" class="form-control text-uppercase"></textarea></div></div></div>
    <div class="modal-footer"><button type="button" class="btn btn-light border btn-sm" data-dismiss="modal">Cancelar</button><button class="btn btn-success btn-sm" type="submit"><i class="fas fa-save mr-1"></i>Registrar movimiento</button></div>
</form></div></div></div>

<div class="modal fade bank-modal" id="bankTransferModal" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><form id="bankTransferForm" enctype="multipart/form-data">
    @csrf<div class="modal-header"><div class="d-flex align-items-center"><span class="bank-modal-title-icon"><i class="fas fa-exchange-alt"></i></span><div><h5 class="modal-title font-weight-bold mb-0">Transferencia bancaria</h5><small class="text-muted">Generará una salida y una entrada relacionadas.</small></div></div><button class="close" data-dismiss="modal">&times;</button></div>
    <div class="modal-body"><div class="form-row"><div class="form-group col-md-6"><label>CUENTA ORIGEN *</label><select name="from_company_bank_account_id" id="bankTransferFrom" class="form-control" required>@include('admin.banks.partials.account-options')</select></div><div class="form-group col-md-6"><label>CUENTA DESTINO *</label><select name="to_company_bank_account_id" id="bankTransferTo" class="form-control" required>@include('admin.banks.partials.account-options')</select></div><div class="form-group col-md-3"><label>FECHA *</label><input type="datetime-local" name="transfer_date" id="bankTransferDate" class="form-control" required></div><div class="form-group col-md-3"><label>MONTO ORIGEN *</label><input type="number" step="0.0001" min="0.0001" name="amount" class="form-control" required></div><div class="form-group col-md-3"><label>TIPO DE CAMBIO</label><input type="number" step="0.000001" min="0.000001" name="exchange_rate" class="form-control"></div><div class="form-group col-md-3"><label>N° OPERACIÓN *</label><input name="operation_number" class="form-control text-uppercase" maxlength="100" required></div><div class="form-group col-md-6"><label>SUSTENTO</label><div class="custom-file"><input type="file" name="file" id="bankTransferFile" class="custom-file-input" accept=".pdf,.jpg,.jpeg,.png,.webp"><label class="custom-file-label" for="bankTransferFile">Seleccionar archivo</label></div></div><div class="form-group col-12"><label>OBSERVACIÓN</label><textarea name="description" rows="3" class="form-control text-uppercase"></textarea></div></div></div>
    <div class="modal-footer"><button type="button" class="btn btn-light border btn-sm" data-dismiss="modal">Cancelar</button><button class="btn btn-success btn-sm" type="submit"><i class="fas fa-exchange-alt mr-1"></i>Transferir</button></div>
</form></div></div></div>

<div class="modal fade bank-modal" id="bankReconciliationModal" tabindex="-1"><div class="modal-dialog modal-xl modal-dialog-centered"><div class="modal-content"><form id="bankReconciliationForm" enctype="multipart/form-data">
    @csrf<div class="modal-header"><div class="d-flex align-items-center"><span class="bank-modal-title-icon"><i class="fas fa-check-double"></i></span><div><h5 class="modal-title font-weight-bold mb-0">Conciliación bancaria</h5><small class="text-muted">Compare el libro del sistema con el estado de cuenta real.</small></div></div><button class="close" data-dismiss="modal">&times;</button></div>
    <div class="modal-body"><div class="form-row align-items-end"><div class="form-group col-md-3"><label>CUENTA *</label><select name="company_bank_account_id" id="bankReconcileAccount" class="form-control" required>@include('admin.banks.partials.account-options')</select></div><div class="form-group col-md-2"><label>PERIODO *</label><input type="month" name="period" id="bankReconcilePeriod" class="form-control" required></div><div class="form-group col-md-2"><label>DESDE *</label><input type="date" name="start_date" id="bankReconcileFrom" class="form-control" required></div><div class="form-group col-md-2"><label>HASTA *</label><input type="date" name="end_date" id="bankReconcileTo" class="form-control" required></div><div class="form-group col-md-2"><label>SALDO BANCO *</label><input type="number" step="0.0001" name="bank_statement_balance" class="form-control" required></div><div class="form-group col-md-1"><button type="button" id="btnLoadReconciliationMovements" class="btn btn-info btn-block"><i class="fas fa-sync"></i></button></div></div><div id="bankReconciliationMovements" class="bank-reconcile-list"><div class="bank-empty">Seleccione cuenta y periodo para cargar movimientos pendientes.</div></div><div class="form-row mt-3"><div class="form-group col-md-6"><label>ESTADO DE CUENTA / SUSTENTO</label><div class="custom-file"><input type="file" name="file" id="bankReconciliationFile" class="custom-file-input" accept=".pdf,.xls,.xlsx,.csv,.jpg,.jpeg,.png,.webp"><label class="custom-file-label" for="bankReconciliationFile">Seleccionar archivo</label></div></div><div class="form-group col-md-6"><label>OBSERVACIÓN</label><input name="observation" class="form-control text-uppercase" maxlength="1500"></div></div></div>
    <div class="modal-footer"><button type="button" class="btn btn-light border btn-sm" data-dismiss="modal">Cancelar</button><button class="btn btn-success btn-sm" type="submit"><i class="fas fa-check-double mr-1"></i>Conciliar seleccionados</button></div>
</form></div></div></div>

<div class="modal fade bank-modal" id="bankCancelModal" tabindex="-1"><div class="modal-dialog modal-md modal-dialog-centered"><div class="modal-content"><form id="bankCancelForm">
    @csrf<input type="hidden" id="bankCancelUrl"><div class="modal-header"><div class="d-flex align-items-center"><span class="bank-modal-title-icon"><i class="fas fa-ban"></i></span><div><h5 class="modal-title font-weight-bold mb-0">Anular y reversar</h5><small class="text-muted" id="bankCancelLabel"></small></div></div><button class="close" data-dismiss="modal">&times;</button></div><div class="modal-body"><div class="alert alert-warning small"><i class="fas fa-exclamation-triangle mr-1"></i>El movimiento original quedará anulado y se generará una reversa que compense el saldo.</div><div class="form-group"><label>MOTIVO *</label><textarea name="cancellation_reason" rows="4" class="form-control" minlength="5" maxlength="1000" required></textarea></div></div><div class="modal-footer"><button type="button" class="btn btn-light border btn-sm" data-dismiss="modal">Cerrar</button><button class="btn btn-danger btn-sm" type="submit"><i class="fas fa-undo-alt mr-1"></i>Anular y reversar</button></div>
</form></div></div></div>
