<!doctype html><html lang="es"><head><meta charset="utf-8"><style>
body{font-family:DejaVu Sans,sans-serif;font-size:9px;color:#24332f}h1{font-size:18px;margin:0;color:#176349}.header{border-bottom:3px solid #176349;padding-bottom:10px;margin-bottom:12px}.meta{width:100%;margin-bottom:12px}.meta td{padding:4px;background:#f2f7f5}.summary{width:100%;margin-bottom:12px}.summary td{padding:8px;border:1px solid #dce6e2;text-align:center}.summary strong{font-size:13px;color:#176349}.items{width:100%;border-collapse:collapse}.items th{background:#176349;color:#fff;padding:6px}.items td{border:1px solid #d8dfdc;padding:5px}.right{text-align:right}.signatures{width:100%;margin-top:46px}.signatures td{text-align:center;padding:0 50px}.line{border-top:1px solid #333;padding-top:5px}
</style></head><body>
<div class="header"><h1>Rendición de Caja Chica</h1><div>{{ $box->code }} · {{ $box->company->business_name ?? $box->company->trade_name }}</div></div>
<table class="meta"><tr><td><b>Periodo:</b> {{ str_pad($box->period_month,2,'0',STR_PAD_LEFT) }}/{{ $box->period_year }}</td><td><b>Vigencia:</b> {{ $box->start_date->format('d/m/Y') }} - {{ $box->end_date->format('d/m/Y') }}</td><td><b>Estado:</b> {{ \App\Models\PettyCashBox::STATUSES[$box->status] ?? $box->status }}</td></tr></table>
<table class="summary"><tr><td>Saldo anterior<br><strong>{{ $box->currency->symbol }} {{ number_format($box->previous_balance,2) }}</strong></td><td>Fondo aprobado<br><strong>{{ $box->currency->symbol }} {{ number_format($box->approved_fund,2) }}</strong></td><td>Fondo inicial<br><strong>{{ $box->currency->symbol }} {{ number_format($box->opening_amount,2) }}</strong></td><td>Total gastado<br><strong>{{ $box->currency->symbol }} {{ number_format($box->total_expenses,2) }}</strong></td><td>Saldo efectivo<br><strong>{{ $box->currency->symbol }} {{ number_format($box->cash_balance,2) }}</strong></td><td>Reposición<br><strong>{{ $box->currency->symbol }} {{ number_format($box->reimbursement_amount,2) }}</strong></td></tr></table>
<table class="items"><thead><tr><th>#</th><th>Fecha</th><th>Comprobante</th><th>RUC</th><th>Proveedor</th><th>Concepto</th><th>Observación</th><th>Importe</th></tr></thead><tbody>
@forelse($box->expenses as $expense)<tr><td>{{ $expense->item_number }}</td><td>{{ $expense->expense_date->format('d/m/Y') }}</td><td>{{ trim($expense->document_type.' '.$expense->document_full_number) }}</td><td>{{ $expense->supplier_ruc }}</td><td>{{ $expense->supplier_name }}</td><td>{{ $expense->concept }}</td><td>{{ $expense->observation }}</td><td class="right">{{ number_format($expense->amount,2) }}</td></tr>@empty<tr><td colspan="8">Sin gastos registrados.</td></tr>@endforelse
<tr><td colspan="7" class="right"><b>TOTAL</b></td><td class="right"><b>{{ number_format($box->total_expenses,2) }}</b></td></tr></tbody></table>
<table class="signatures"><tr><td><div class="line">{{ $box->responsible_name }}<br>Responsable · DNI {{ $box->responsible_dni }}</div></td><td><div class="line">{{ $box->supervisor_name }}<br>Supervisor · DNI {{ $box->supervisor_dni }}</div></td></tr></table>
</body></html>
