<div class="modal fade general-cash-modal" id="generalCashBoxModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><form id="generalCashBoxForm">
    @csrf<input type="hidden" id="general_cash_box_id">
    <div class="modal-header"><div class="d-flex align-items-center"><span class="general-cash-modal-title-icon"><i class="fas fa-cash-register"></i></span><div><h5 class="modal-title mb-0" id="generalCashBoxModalTitle">Nueva Caja General</h5><small>Configura una caja física independiente por empresa y moneda.</small></div></div><button type="button" class="close" data-dismiss="modal">&times;</button></div>
    <div class="modal-body"><div class="form-row">
        <div class="form-group col-md-6"><label>EMPRESA *</label><select name="company_id" id="general_cash_company_id" class="form-control"><option value="">Seleccione</option>@foreach($companies as $company)<option value="{{ $company->id }}">{{ $company->trade_name ?: $company->business_name }}</option>@endforeach</select></div>
        <div class="form-group col-md-6"><label>MONEDA *</label><select name="currency_id" id="general_cash_currency_id" class="form-control"><option value="">Seleccione</option>@foreach($currencies as $currency)<option value="{{ $currency->id }}">{{ $currency->code }} - {{ $currency->description }}</option>@endforeach</select></div>
        <div class="form-group col-md-8"><label>NOMBRE DE LA CAJA *</label><input name="name" id="general_cash_name" class="form-control" maxlength="120"></div>
        <div class="form-group col-md-4"><label>ESTADO *</label><select name="status" id="general_cash_status" class="form-control"><option value="ACTIVE">Activa</option><option value="INACTIVE">Inactiva</option></select></div>
        <div class="form-group col-12"><label>RESPONSABLE</label><select name="responsible_user_id" id="general_cash_responsible_user_id" class="form-control"><option value="">No asignado</option>@foreach($users as $user)<option value="{{ $user->id }}">{{ trim($user->name.' '.$user->lastname) }}</option>@endforeach</select></div>
        <div class="form-group col-12 mb-0"><label>DESCRIPCIÓN</label><textarea name="description" id="general_cash_description" class="form-control" rows="3"></textarea></div>
    </div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-dismiss="modal">Cancelar</button><button class="btn btn-success" type="submit"><i class="fas fa-save mr-1"></i>Guardar</button></div>
</form></div></div></div>

<div class="modal fade general-cash-modal" id="generalCashFundingModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><form id="generalCashFundingForm" enctype="multipart/form-data">
    @csrf<input type="hidden" name="idempotency_key" id="general_cash_funding_key">
    <div class="modal-header"><div class="d-flex align-items-center"><span class="general-cash-modal-title-icon is-bank"><i class="fas fa-university"></i></span><div><h5 class="modal-title mb-0">Ingresar efectivo desde banco</h5><small>Genera un egreso bancario y un ingreso relacionado en Caja General.</small></div></div><button type="button" class="close" data-dismiss="modal">&times;</button></div>
    <div class="modal-body"><div class="alert alert-info py-2"><i class="fas fa-link mr-1"></i>Banco y caja se actualizarán dentro de una sola transacción.</div><div class="form-row">
        <div class="form-group col-md-6"><label>CAJA GENERAL *</label><select name="general_cash_box_id" id="general_cash_funding_box_id" class="form-control general-cash-box-select"><option value="">Seleccione</option>@foreach($boxes as $box)<option value="{{ $box->id }}" data-company="{{ $box->company_id }}" data-currency="{{ $box->currency_id }}">{{ $box->code }} · {{ $box->name }} · {{ $box->currency?->code }}</option>@endforeach</select></div>
        <div class="form-group col-md-6"><label>CUENTA BANCARIA ORIGEN *</label><select name="company_bank_account_id" id="general_cash_bank_account_id" class="form-control"><option value="">Seleccione primero una caja</option></select><small id="generalCashBankBalance" class="form-text text-muted"></small></div>
        <div class="form-group col-md-4"><label>FECHA *</label><input type="date" name="movement_date" class="form-control" value="{{ now()->toDateString() }}"></div>
        <div class="form-group col-md-4"><label>MONTO RETIRADO *</label><input type="number" name="amount" min="0.01" step="0.01" class="form-control"></div>
        <div class="form-group col-md-4"><label>NRO. OPERACIÓN *</label><input name="operation_number" maxlength="100" class="form-control"></div>
        <div class="form-group col-md-6"><label>RESPONSABLE</label><select name="responsible_user_id" class="form-control"><option value="">Seleccione</option>@foreach($users as $user)<option value="{{ $user->id }}">{{ trim($user->name.' '.$user->lastname) }}</option>@endforeach</select></div>
        <div class="form-group col-md-6"><label>RESPONSABLE EXTERNO / REFERENCIA</label><input name="responsible_name" maxlength="150" class="form-control"></div>
        <div class="form-group col-md-6"><label>SUSTENTO OPCIONAL</label><input type="file" name="support_file" class="form-control-file" accept=".pdf,.jpg,.jpeg,.png,.webp,.xls,.xlsx"></div>
        <div class="form-group col-12 mb-0"><label>OBSERVACIÓN</label><textarea name="observation" class="form-control" rows="3"></textarea></div>
    </div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-dismiss="modal">Cancelar</button><button class="btn btn-primary" type="submit"><i class="fas fa-exchange-alt mr-1"></i>Ingresar efectivo</button></div>
</form></div></div></div>

<div class="modal fade general-cash-modal" id="generalCashExpenseModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-xl modal-dialog-centered"><div class="modal-content"><form id="generalCashExpenseForm" enctype="multipart/form-data">
    @csrf<input type="hidden" name="idempotency_key" id="general_cash_expense_key">
    <div class="modal-header"><div class="d-flex align-items-center"><span class="general-cash-modal-title-icon is-expense"><i class="fas fa-receipt"></i></span><div><h5 class="modal-title mb-0">Registrar gasto general</h5><small>El importe se descontará inmediatamente del efectivo disponible.</small></div></div><button type="button" class="close" data-dismiss="modal">&times;</button></div>
    <div class="modal-body"><div class="form-row">
        <div class="form-group col-lg-4"><label>CAJA GENERAL *</label><select name="general_cash_box_id" id="general_cash_expense_box_id" class="form-control general-cash-box-select"><option value="">Seleccione</option>@foreach($boxes as $box)<option value="{{ $box->id }}">{{ $box->code }} · {{ $box->name }} · Saldo {{ $box->currency?->symbol }} {{ number_format($box->current_balance,2) }}</option>@endforeach</select></div>
        <div class="form-group col-lg-3"><label>FECHA *</label><input type="date" name="expense_date" class="form-control" value="{{ now()->toDateString() }}"></div>
        <div class="form-group col-lg-5"><label>TIPO DE GASTO *</label><select name="expense_type" class="form-control"><option value="GASOLINA">Gasolina / combustible</option><option value="MOVILIDAD">Movilidad</option><option value="PAGO_PERSONA">Pago a persona</option><option value="PAGO_PROVEEDOR">Pago a proveedor</option><option value="SERVICIO_MENOR">Servicio menor</option><option value="GASTO_ADMINISTRATIVO">Gasto administrativo</option><option value="OTRO">Otro gasto</option></select></div>
        <div class="form-group col-lg-4"><label>PROVEEDOR REGISTRADO</label><select name="supplier_id" id="general_cash_expense_supplier_id" class="form-control"><option value="">No aplica</option>@foreach($suppliers as $supplier)<option value="{{ $supplier->id }}" data-name="{{ $supplier->business_name }}" data-ruc="{{ $supplier->ruc }}">{{ $supplier->ruc }} · {{ $supplier->short_name ?: $supplier->business_name }}</option>@endforeach</select></div>
        <div class="form-group col-lg-5"><label>PROVEEDOR / PERSONA / RESPONSABLE *</label><input name="person_name" id="general_cash_expense_person_name" maxlength="180" class="form-control"></div>
        <div class="form-group col-lg-3"><label>RUC / DNI</label><input name="identity_document" id="general_cash_expense_identity" maxlength="20" class="form-control"></div>
        <div class="form-group col-12"><label>CONCEPTO *</label><input name="concept" maxlength="255" class="form-control"></div>
        <div class="form-group col-lg-3"><label>TIPO COMPROBANTE *</label><select name="document_type" id="general_cash_expense_document_type" class="form-control"><option value="FACTURA">Factura</option><option value="BOLETA">Boleta</option><option value="RECIBO_HONORARIOS">Recibo por honorarios</option><option value="RECIBO_INTERNO">Recibo interno</option><option value="SIN_COMPROBANTE">Sin comprobante</option></select></div>
        <div class="form-group col-lg-2"><label>SERIE</label><input name="document_series" class="form-control" maxlength="30"></div>
        <div class="form-group col-lg-3"><label>NÚMERO</label><input name="document_number" class="form-control" maxlength="80"></div>
        <div class="form-group col-lg-2"><label>IMPORTE *</label><input type="number" name="amount" min="0.01" step="0.01" class="form-control"></div>
        <div class="form-group col-lg-2"><label>AFECTA IGV *</label><select name="affects_igv" id="general_cash_expense_affects_igv" class="form-control"><option value="0">No</option><option value="1">Sí</option></select></div>
        <div class="form-group col-md-6"><label>COMPROBANTE / RECIBO</label><input type="file" name="receipt_file" class="form-control-file" accept=".pdf,.jpg,.jpeg,.png,.webp"></div>
        <div class="form-group col-md-6"><label>CONSTANCIA / VOUCHER DE PAGO</label><input type="file" name="payment_file" class="form-control-file" accept=".pdf,.jpg,.jpeg,.png,.webp"></div>
        <div class="form-group col-12 mb-0"><label>OBSERVACIÓN</label><textarea name="observation" class="form-control" rows="3"></textarea></div>
    </div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-dismiss="modal">Cancelar</button><button class="btn btn-danger" type="submit"><i class="fas fa-save mr-1"></i>Registrar gasto</button></div>
</form></div></div></div>

<div class="modal fade general-cash-modal" id="generalCashReconciliationModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><form id="generalCashReconciliationForm" enctype="multipart/form-data">
    @csrf<div class="modal-header"><div class="d-flex align-items-center"><span class="general-cash-modal-title-icon is-reconcile"><i class="fas fa-balance-scale"></i></span><div><h5 class="modal-title mb-0">Arqueo / cierre de Caja General</h5><small>Registra el saldo esperado, efectivo físico y cualquier diferencia.</small></div></div><button type="button" class="close" data-dismiss="modal">&times;</button></div>
    <div class="modal-body"><div class="form-row">
        <div class="form-group col-md-6"><label>CAJA GENERAL *</label><select name="general_cash_box_id" id="general_cash_reconciliation_box_id" class="form-control general-cash-box-select"><option value="">Seleccione</option>@foreach($boxes as $box)<option value="{{ $box->id }}" data-balance="{{ $box->current_balance }}">{{ $box->code }} · {{ $box->name }}</option>@endforeach</select></div>
        <div class="form-group col-md-6"><label>FECHA DE ARQUEO *</label><input type="datetime-local" name="reconciliation_date" class="form-control" value="{{ now()->format('Y-m-d\TH:i') }}"></div>
        <div class="form-group col-md-4"><label>SALDO ESPERADO</label><input id="general_cash_system_balance" class="form-control" readonly value="0.00"></div>
        <div class="form-group col-md-4"><label>SALDO FÍSICO CONTADO *</label><input type="number" name="physical_balance" id="general_cash_physical_balance" min="0" step="0.01" class="form-control"></div>
        <div class="form-group col-md-4"><label>DIFERENCIA</label><input id="general_cash_difference" class="form-control" readonly value="0.00"></div>
        <div class="form-group col-md-6"><label>RESPONSABLE</label><select name="responsible_user_id" class="form-control"><option value="">Seleccione</option>@foreach($users as $user)<option value="{{ $user->id }}">{{ trim($user->name.' '.$user->lastname) }}</option>@endforeach</select></div>
        <div class="form-group col-md-6"><label>RESPONSABLE EXTERNO</label><input name="responsible_name" maxlength="150" class="form-control"></div>
        <div class="form-group col-md-6"><label>SUSTENTO OPCIONAL</label><input type="file" name="support_file" class="form-control-file" accept=".pdf,.jpg,.jpeg,.png,.webp,.xls,.xlsx"></div>
        <div class="form-group col-12 mb-0"><label>OBSERVACIÓN</label><textarea name="observation" class="form-control" rows="3"></textarea></div>
    </div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-dismiss="modal">Cancelar</button><button class="btn btn-warning" type="submit"><i class="fas fa-balance-scale mr-1"></i>Registrar arqueo</button></div>
</form></div></div></div>

<div class="modal fade general-cash-modal" id="generalCashDetailModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-xl modal-dialog-centered"><div class="modal-content">
    <div class="modal-header"><div class="d-flex align-items-center"><span class="general-cash-modal-title-icon"><i class="fas fa-cash-register"></i></span><div><h5 class="modal-title mb-0" id="generalCashDetailTitle">Detalle de Caja General</h5><small id="generalCashDetailSubtitle">Movimientos, gastos, documentos, arqueos y auditoría.</small></div></div><button type="button" class="close" data-dismiss="modal">&times;</button></div>
    <ul class="nav general-cash-detail-tabs" role="tablist"><li class="nav-item"><a class="nav-link active" data-toggle="tab" href="#generalCashSummaryTab">Resumen</a></li><li class="nav-item"><a class="nav-link" data-toggle="tab" href="#generalCashMovementsTab">Movimientos</a></li><li class="nav-item"><a class="nav-link" data-toggle="tab" href="#generalCashExpensesTab">Gastos</a></li><li class="nav-item"><a class="nav-link" data-toggle="tab" href="#generalCashDocumentsTab">Documentos</a></li><li class="nav-item"><a class="nav-link" data-toggle="tab" href="#generalCashReconciliationsTab">Arqueos</a></li><li class="nav-item"><a class="nav-link" data-toggle="tab" href="#generalCashAuditTab">Auditoría</a></li></ul>
    <div class="modal-body general-cash-detail-content"><div class="tab-content"><div class="tab-pane fade show active" id="generalCashSummaryTab"></div><div class="tab-pane fade" id="generalCashMovementsTab"></div><div class="tab-pane fade" id="generalCashExpensesTab"></div><div class="tab-pane fade" id="generalCashDocumentsTab"></div><div class="tab-pane fade" id="generalCashReconciliationsTab"></div><div class="tab-pane fade" id="generalCashAuditTab"></div></div></div>
    <div class="modal-footer"><button class="btn btn-light" data-dismiss="modal">Cerrar</button></div>
</div></div></div>
